# Generated by Django 4.2.4 on 2023-08-08 14:32

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("LittleLemonAPI", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProxy",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("auth.user",),
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Categories"},
        ),
    ]
