# Generated by Django 4.2.4 on 2023-08-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0005_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
